name: Deploy to VPS

# Deploying to my VPS

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dnd-bot-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dnd-bot-app:latest

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts

      - name: Deploy on VPS using Docker Compose
        run: |
          ssh $VPS_USER@$VPS_HOST << 'EOF'
            cd /home/$VPS_USER/dnd-bot-app
            git pull origin main
            docker compose pull
            docker compose up -d --remove-orphans
          EOF
